### PR TITLE
Attempt bootSound implementation

### PR DESCRIPTION
**Pull request by rpdistiso**

### CODE REVIEW

**Comment by rpdistiso** [comment]
I'm having issues building libgui

**Comment by Maschell** [comment]
This doesn't look like anything that's in a mergable state. Either keep it marked as a Draft or close the PR and reopen it once it's finished

**Comment by Maschell** [comment]
The PR doesn't even change anything. It's adds a bunch of unused files and removes some empty lines. Please reopen the PR if you actually implemented the splash sound

**Comment by rpdistiso** [comment]
I fixed some missing includes and fixed _SYSSwitchTo using an integer

**Pull request closed without merging**
